name: agro_inteli_colombia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  google_maps_flutter: ^2.2.0
  geolocator: ^10.0.0
  http: ^1.1.0
  uuid: ^4.0.0
  image_picker: ^1.1.0
  badges: ^3.1.2
  path_provider: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  badges: ^3.1.2
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#EEEEEEEE"
  adaptive_icon_foreground: "assets/icons/logo.png"
